#!/bin/bash
# Backup Script for REChain Network Solutions LLC
# Complete backup solution for blockchain data and configurations

set -e

# Configuration
BACKUP_DIR="${1:-./backups}"
RETENTION_DAYS="${2:-30}"
CHAIN_NAME="${3:-rechain}"

echo "💾 Creating backup for $CHAIN_NAME..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}[BACKUP]${NC} $1"
}

print_section() {
    echo -e "${BLUE}[SECTION]${NC} $1"
}

# Create backup directory
create_backup_dir() {
    print_section "Creating backup directory..."

    mkdir -p "$BACKUP_DIR"
    chmod 700 "$BACKUP_DIR"

    print_status "Backup directory created: $BACKUP_DIR"
}

# Backup chain data
backup_chain_data() {
    print_section "Backing up chain data..."

    # Create timestamped backup
    TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
    BACKUP_NAME="${CHAIN_NAME}_backup_${TIMESTAMP}"
    BACKUP_PATH="$BACKUP_DIR/$BACKUP_NAME"

    mkdir -p "$BACKUP_PATH"

    # Stop services if running
    print_status "Stopping services..."
    # systemctl stop rechain-validator 2>/dev/null || true
    # systemctl stop rechain-node 2>/dev/null || true

    # Backup chain data
    if [[ -d "./chains/$CHAIN_NAME" ]]; then
        print_status "Backing up chain data..."
        cp -r "./chains/$CHAIN_NAME" "$BACKUP_PATH/chain-data/"
    fi

    # Backup validator data
    if [[ -d "./validators" ]]; then
        print_status "Backing up validator data..."
        cp -r "./validators" "$BACKUP_PATH/validator-data/"
    fi

    # Backup keystore
    if [[ -d "./keystore" ]]; then
        print_status "Backing up keystore..."
        cp -r "./keystore" "$BACKUP_PATH/keystore-backup/"
    fi

    print_status "Chain data backup completed"
}

# Backup configurations
backup_configurations() {
    print_section "Backing up configurations..."

    CONFIG_BACKUP="$BACKUP_PATH/config-backup"
    mkdir -p "$CONFIG_BACKUP"

    # Backup configuration files
    print_status "Backing up configuration files..."
    cp -r "./config" "$CONFIG_BACKUP/" 2>/dev/null || true
    cp ".env"* "$CONFIG_BACKUP/" 2>/dev/null || true
    cp "*.toml" "$CONFIG_BACKUP/" 2>/dev/null || true
    cp "*.json" "$CONFIG_BACKUP/" 2>/dev/null || true

    # Backup scripts
    print_status "Backing up scripts..."
    cp -r "./scripts" "$CONFIG_BACKUP/scripts-backup/" 2>/dev/null || true

    # Backup monitoring configuration
    print_status "Backing up monitoring configuration..."
    cp -r "./monitoring" "$CONFIG_BACKUP/monitoring-backup/" 2>/dev/null || true

    print_status "Configuration backup completed"
}

# Backup database
backup_database() {
    print_section "Backing up database..."

    if command -v pg_dump &> /dev/null; then
        print_status "Backing up PostgreSQL database..."
        pg_dump -h localhost -U rechain rechain_dev > "$BACKUP_PATH/database.sql"
    fi

    if command -v mongodump &> /dev/null; then
        print_status "Backing up MongoDB database..."
        mongodump --out "$BACKUP_PATH/mongodb-backup"
    fi

    print_status "Database backup completed"
}

# Create archive
create_archive() {
    print_section "Creating compressed archive..."

    ARCHIVE_NAME="${BACKUP_NAME}.tar.gz"
    ARCHIVE_PATH="$BACKUP_DIR/$ARCHIVE_NAME"

    print_status "Creating archive: $ARCHIVE_NAME"
    cd "$BACKUP_DIR"
    tar -czf "$ARCHIVE_NAME" "$BACKUP_NAME"

    # Remove uncompressed backup
    rm -rf "$BACKUP_NAME"

    print_status "Archive created: $ARCHIVE_PATH"
}

# Calculate checksum
create_checksum() {
    print_section "Creating checksum..."

    ARCHIVE_NAME="${BACKUP_NAME}.tar.gz"
    ARCHIVE_PATH="$BACKUP_DIR/$ARCHIVE_NAME"

    print_status "Creating checksum..."
    cd "$BACKUP_DIR"

    if command -v sha256sum &> /dev/null; then
        sha256sum "$ARCHIVE_NAME" > "${ARCHIVE_NAME}.sha256"
    fi

    if command -v gpg &> /dev/null; then
        print_status "Creating GPG signature..."
        gpg --sign --detach-sign "$ARCHIVE_NAME"
    fi

    print_status "Checksum created"
}

# Cleanup old backups
cleanup_old_backups() {
    print_section "Cleaning up old backups..."

    print_status "Removing backups older than $RETENTION_DAYS days..."

    find "$BACKUP_DIR" -name "*.tar.gz" -type f -mtime +$RETENTION_DAYS -delete
    find "$BACKUP_DIR" -name "*.sha256" -type f -mtime +$RETENTION_DAYS -delete
    find "$BACKUP_DIR" -name "*.sig" -type f -mtime +$RETENTION_DAYS -delete

    print_status "Cleanup completed"
}

# Generate backup report
generate_backup_report() {
    print_section "Generating backup report..."

    REPORT_FILE="$BACKUP_DIR/backup-report.txt"

    cat > "$REPORT_FILE" << EOF
# REChain Backup Report
Generated by REChain Network Solutions LLC

## Backup Information
- **Backup Date**: $(date)
- **Chain Name**: $CHAIN_NAME
- **Backup Type**: Full backup
- **Archive Name**: ${BACKUP_NAME}.tar.gz
- **Archive Location**: $BACKUP_DIR

## Backup Contents
- ✅ Chain data and state
- ✅ Validator configurations
- ✅ Keystore and keys
- ✅ Application configurations
- ✅ Database backups
- ✅ Monitoring configurations
- ✅ Checksums and signatures

## Archive Information
- **Size**: $(du -sh "$BACKUP_DIR/$ARCHIVE_NAME" 2>/dev/null | cut -f1)
- **SHA256**: $(cat "$BACKUP_DIR/$ARCHIVE_NAME.sha256" 2>/dev/null)
- **Encrypted**: $(if [[ -f "$BACKUP_DIR/$ARCHIVE_NAME.gpg" ]]; then echo "Yes"; else echo "No"; fi)

## Next Steps
1. Store backup in secure location
2. Test backup restoration
3. Verify backup integrity
4. Update backup documentation

## Support
For backup assistance:
- **Email**: info@rechain.network
- **Documentation**: https://docs.rechain.network
- **GitHub**: https://github.com/REChain-Network-Solutions/SDK
EOF

    print_status "Backup report generated: $REPORT_FILE"
}

# Upload to remote storage (optional)
upload_backup() {
    print_section "Uploading backup to remote storage..."

    # Example: Upload to AWS S3 (if configured)
    if command -v aws &> /dev/null && [[ -n "$AWS_ACCESS_KEY_ID" ]]; then
        print_status "Uploading to AWS S3..."
        aws s3 cp "$BACKUP_DIR/$ARCHIVE_NAME" "s3://rechain-backups/$CHAIN_NAME/"
        aws s3 cp "$BACKUP_DIR/$ARCHIVE_NAME.sha256" "s3://rechain-backups/$CHAIN_NAME/"
    fi

    # Example: Upload to Google Cloud Storage (if configured)
    if command -v gsutil &> /dev/null; then
        print_status "Uploading to Google Cloud Storage..."
        gsutil cp "$BACKUP_DIR/$ARCHIVE_NAME" "gs://rechain-backups/$CHAIN_NAME/"
        gsutil cp "$BACKUP_DIR/$ARCHIVE_NAME.sha256" "gs://rechain-backups/$CHAIN_NAME/"
    fi

    print_status "Remote upload completed"
}

# Main backup flow
main() {
    print_status "=== REChain Network Solutions LLC - Complete Backup ==="

    create_backup_dir
    backup_chain_data
    backup_configurations
    backup_database
    create_archive
    create_checksum
    cleanup_old_backups
    generate_backup_report
    upload_backup

    print_status "🎉 Backup completed successfully!"
    print_status ""
    print_status "=== Backup Summary ==="
    print_status "Archive: $BACKUP_DIR/$ARCHIVE_NAME"
    print_status "Size: $(du -sh "$BACKUP_DIR/$ARCHIVE_NAME" 2>/dev/null | cut -f1)"
    print_status "Report: $BACKUP_DIR/backup-report.txt"
    print_status ""
    print_status "Store this backup in a secure location!"
}

# Handle script arguments
case "${1:-}" in
    "help"|"-h"|"--help")
        echo "Usage: $0 [BACKUP_DIR] [RETENTION_DAYS] [CHAIN_NAME]"
        echo ""
        echo "Arguments:"
        echo "  BACKUP_DIR      Backup destination directory (default: ./backups)"
        echo "  RETENTION_DAYS  Days to retain backups (default: 30)"
        echo "  CHAIN_NAME      Chain name for backup (default: rechain)"
        echo ""
        echo "Examples:"
        echo "  $0                           # Use all defaults"
        echo "  $0 /mnt/backups 60          # 60-day retention"
        echo "  $0 /backup rechain-mainnet  # Custom chain name"
        exit 0
        ;;
    *)
        main
        ;;
esac