#!/bin/bash
# SDK Generator Script - REChain Network Solutions LLC
# Generates complete SDK for the REChain ecosystem

set -e

# Configuration
PROJECT_NAME="${1:-rechain-dapp}"
LANGUAGE="${2:-typescript}"
OUTPUT_DIR="${3:-./sdk}"

echo "🔧 Generating $LANGUAGE SDK for $PROJECT_NAME..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${GREEN}[SDK]${NC} $1"
}

print_section() {
    echo -e "${BLUE}[GEN]${NC} $1"
}

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Generate TypeScript SDK
generate_typescript_sdk() {
    print_section "Generating TypeScript SDK..."

    # Generate package.json
    cat > "$OUTPUT_DIR/package.json" << EOF
{
  "name": "$PROJECT_NAME-sdk",
  "version": "1.0.0",
  "description": "REChain Network Solutions LLC - Complete SDK for $PROJECT_NAME",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc",
    "test": "jest",
    "lint": "eslint src --ext .ts",
    "format": "prettier --write src"
  },
  "dependencies": {
    "@polkadot/api": "^10.0.0",
    "@polkadot/types": "^10.0.0",
    "@polkadot/util": "^10.0.0",
    "axios": "^1.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0",
    "jest": "^29.0.0",
    "eslint": "^8.0.0",
    "prettier": "^3.0.0"
  }
}
EOF

    # Generate TypeScript configuration
    cat > "$OUTPUT_DIR/tsconfig.json" << EOF
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "resolveJsonModule": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
EOF

    # Generate main SDK file
    cat > "$OUTPUT_DIR/src/index.ts" << EOF
// $PROJECT_NAME SDK - Generated by REChain Network Solutions LLC
// Complete SDK for interacting with the REChain ecosystem

import { ApiPromise, WsProvider } from '@polkadot/api';
import { Keyring } from '@polkadot/keyring';

/**
 * REChain SDK Configuration
 */
export interface SDKConfig {
  endpoint: string;
  timeout?: number;
  retries?: number;
}

/**
 * Complete REChain SDK Client
 */
export class REChainSDK {
  private api: ApiPromise | null = null;
  private config: SDKConfig;
  private keyring: Keyring;

  constructor(config: SDKConfig) {
    this.config = config;
    this.keyring = new Keyring({ type: 'sr25519' });
  }

  /**
   * Initialize SDK connection
   */
  async initialize(): Promise<void> {
    const provider = new WsProvider(this.config.endpoint);

    this.api = await ApiPromise.create({
      provider,
      timeout: this.config.timeout || 60000,
    });

    await this.api.isReady;
    console.log('🚀 REChain SDK initialized successfully');
  }

  /**
   * Web3 DApp Management
   */
  async registerDApp(name: string, description: string): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.web3.registerDapp(
      name,
      description
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * Web4 Domain Registration
   */
  async registerDomain(domain: string, contentHash: string): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.web4.registerDomain(
      domain,
      contentHash
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * Web5 Decentralized Identity
   */
  async createDID(did: string, publicKeys: string[]): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.web5.createDid(
      did,
      publicKeys,
      []
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * DeFi Token Creation
   */
  async createToken(name: string, symbol: string, decimals: number, supply: bigint): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.defi.createToken(
      name,
      symbol,
      decimals,
      supply
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * NFT Collection Creation
   */
  async createNFTCollection(name: string, description: string, maxSupply?: number): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.nft.createNftCollection(
      name,
      description,
      maxSupply,
      500 // 5% royalty
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * Cross-chain Bridge Transfer
   */
  async initiateCrossChainTransfer(
    bridgeId: string,
    sourceAsset: string,
    targetChain: string,
    recipient: string,
    amount: bigint
  ): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.bridge.initiateCrossChainTransfer(
      bridgeId,
      sourceAsset,
      targetChain,
      "TARGET_ASSET",
      recipient,
      amount
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * Governance Proposal Creation
   */
  async createProposal(title: string, description: string): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.governance.createProposal(
      title,
      description,
      null
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * Oracle Data Submission
   */
  async submitOracleData(feedName: string, key: string, value: number): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.oracle.submitOracleData(
      feedName,
      key,
      value.toString(),
      value
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * ZKP Verification
   */
  async submitZKP(proofId: string, proofData: string, publicInputs: string): Promise<string> {
    if (!this.api) throw new Error('SDK not initialized');

    const tx = this.api.tx.zkp.submitZkp(
      proofId,
      proofData,
      publicInputs
    );

    const result = await tx.signAndSend(this.keyring.addFromUri('//Alice'));
    return result.toString();
  }

  /**
   * Get account balance
   */
  async getBalance(account: string): Promise<bigint> {
    if (!this.api) throw new Error('SDK not initialized');

    const balance = await this.api.query.system.account(account);
    return balance.data.free.toBigInt();
  }

  /**
   * Get block number
   */
  async getBlockNumber(): Promise<number> {
    if (!this.api) throw new Error('SDK not initialized');

    const header = await this.api.rpc.chain.getHeader();
    return header.number.toNumber();
  }

  /**
   * Disconnect SDK
   */
  async disconnect(): Promise<void> {
    if (this.api) {
      await this.api.disconnect();
      this.api = null;
    }
  }
}

/**
 * SDK Error types
 */
export class SDKError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SDKError';
  }
}

/**
 * Helper functions
 */
export const Utils = {
  /**
   * Generate keypair from seed
   */
  generateKeypair(seed: string) {
    const keyring = new Keyring({ type: 'sr25519' });
    return keyring.addFromUri(seed);
  },

  /**
   * Format balance for display
   */
  formatBalance(balance: bigint, decimals: number = 12): string {
    const divisor = BigInt(10 ** decimals);
    const integerPart = balance / divisor;
    const fractionalPart = balance % divisor;

    return `${integerPart}.${fractionalPart.toString().padStart(decimals, '0')} RECH`;
  },

  /**
   * Convert address format
   */
  convertAddress(address: string, targetFormat: number = 42): string {
    // Address conversion logic
    return address; // Placeholder
  }
};

export default REChainSDK;
EOF

    # Generate test file
    cat > "$OUTPUT_DIR/src/test.ts" << EOF
// SDK Tests - Generated by REChain Network Solutions LLC

import REChainSDK from './index';

describe('REChain SDK', () => {
  let sdk: REChainSDK;

  beforeAll(async () => {
    sdk = new REChainSDK({
      endpoint: 'ws://localhost:9944',
      timeout: 30000,
    });

    await sdk.initialize();
  });

  afterAll(async () => {
    await sdk.disconnect();
  });

  test('should initialize successfully', () => {
    expect(sdk).toBeDefined();
  });

  test('should get current block number', async () => {
    const blockNumber = await sdk.getBlockNumber();
    expect(typeof blockNumber).toBe('number');
    expect(blockNumber).toBeGreaterThan(0);
  });

  test('should get account balance', async () => {
    const balance = await sdk.getBalance('//Alice');
    expect(typeof balance).toBe('bigint');
  });

  test('should create governance proposal', async () => {
    const result = await sdk.createProposal(
      'Test Proposal',
      'This is a test proposal for SDK testing'
    );
    expect(result).toBeDefined();
  });
});
EOF

    # Generate README for SDK
    cat > "$OUTPUT_DIR/README.md" << EOF
# $PROJECT_NAME SDK

Complete SDK for building applications on the REChain Network Solutions LLC blockchain ecosystem.

## Features

- 🚀 **Complete Ecosystem Support**: Web3, Web4, Web5, DeFi, NFT, Bridge, Governance, Oracle, ZKP
- 🔧 **TypeScript Support**: Full TypeScript definitions and type safety
- 📦 **Easy Integration**: Simple API for complex blockchain operations
- 🛡️ **Error Handling**: Comprehensive error handling and validation
- 📚 **Documentation**: Complete documentation and examples

## Installation

\`\`\`bash
npm install $PROJECT_NAME-sdk
\`\`\`

## Quick Start

\`\`\`typescript
import REChainSDK from '$PROJECT_NAME-sdk';

async function main() {
  // Initialize SDK
  const sdk = new REChainSDK({
    endpoint: 'ws://localhost:9944'
  });

  await sdk.initialize();

  // Create DApp
  await sdk.registerDApp('MyDApp', 'My awesome DApp');

  // Register domain
  await sdk.registerDomain('mydapp.web4', 'QmYwAPJzv5CZsnAztmj5DrE8yQkCjXaieQaxZ');

  // Create governance proposal
  await sdk.createProposal('Improve Network', 'Make the network better');

  await sdk.disconnect();
}

main().catch(console.error);
\`\`\`

## API Reference

### Web3 (DApps)
- \`registerDApp(name, description)\`: Register new DApp
- \`deployContract(dappName, metadata, bytecode, abi, gasOpt)\`: Deploy smart contract

### Web4 (Domains)
- \`registerDomain(domain, contentHash)\`: Register blockchain domain
- \`updateDomain(domain, newContentHash)\`: Update domain content

### Web5 (Identity)
- \`createDID(did, publicKeys, services)\`: Create decentralized identity
- \`issueCredential(subjectDID, credentialId, type, data, expiry)\`: Issue verifiable credential

### DeFi
- \`createToken(name, symbol, decimals, supply)\`: Create new token
- \`createLiquidityPool(name, tokenA, tokenB, amountA, amountB)\`: Create AMM pool
- \`swapTokens(poolName, tokenIn, amountIn, minOut)\`: Token swap
- \`createLendingPool(token, interestRate, reserveFactor)\`: Create lending pool

### NFT
- \`createNFTCollection(name, description, maxSupply)\`: Create NFT collection
- \`mintNFT(collection, tokenId, metadata, to)\`: Mint NFT
- \`listNFT(collection, tokenId, price, duration)\`: List on marketplace

### Bridge
- \`createBridge(id, targetChain, threshold, fee)\`: Create cross-chain bridge
- \`initiateCrossChainTransfer(bridgeId, asset, targetChain, recipient, amount)\`: Cross-chain transfer

### Governance
- \`createProposal(title, description, metadata)\`: Create governance proposal
- \`voteOnProposal(proposalId, direction)\`: Vote on proposal

### Oracle
- \`createOracleFeed(name, description, operators, staleness, submissions, reward)\`: Create data feed
- \`submitOracleData(feedName, key, value, rawValue)\`: Submit data

### ZKP
- \`registerVerificationKey(id, key, description, curve)\`: Register ZKP circuit
- \`submitZKP(proofId, proofData, publicInputs)\`: Submit proof

## Configuration

\`\`\`typescript
const config: SDKConfig = {
  endpoint: 'ws://localhost:9944',  // RPC endpoint
  timeout: 30000,                   // Request timeout
  retries: 3,                       // Retry attempts
};

const sdk = new REChainSDK(config);
\`\`\`

## Error Handling

\`\`\`typescript
try {
  await sdk.registerDApp('MyApp', 'Description');
} catch (error) {
  if (error instanceof SDKError) {
    console.error('SDK Error:', error.message);
  } else {
    console.error('Unknown error:', error);
  }
}
\`\`\`

## License

Licensed under the GPL-3.0 License by REChain Network Solutions LLC.

## Support

- **Email**: info@rechain.network
- **Documentation**: https://docs.rechain.network
- **GitHub**: https://github.com/REChain-Network-Solutions/SDK
EOF

    print_status "TypeScript SDK generated successfully."
}

# Generate Rust SDK
generate_rust_sdk() {
    print_section "Generating Rust SDK..."

    # Generate Cargo.toml
    cat > "$OUTPUT_DIR/Cargo.toml" << EOF
[package]
name = "$PROJECT_NAME-sdk"
version = "1.0.0"
description = "REChain Network Solutions LLC - Complete Rust SDK for $PROJECT_NAME"
edition = "2021"
license = "GPL-3.0-only"
authors = ["REChain Network Solutions LLC <info@rechain.network>"]

[dependencies]
async-trait = "0.1"
codec = { package = "parity-scale-codec", version = "3.6", default-features = false, features = ["derive"] }
futures = "0.3"
jsonrpsee = { version = "0.20", features = ["ws-client", "macros"] }
log = "0.4"
scale-info = { version = "2.5", default-features = false, features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subxt = "0.29"
tokio = { version = "1.0", features = ["full"] }
url = "2.3"

[dev-dependencies]
env_logger = "0.10"
EOF

    # Generate lib.rs
    cat > "$OUTPUT_DIR/src/lib.rs" << EOF
// $PROJECT_NAME Rust SDK - Generated by REChain Network Solutions LLC
// Complete SDK for interacting with the REChain ecosystem

pub mod web3;
pub mod web4;
pub mod web5;
pub mod defi;
pub mod nft;
pub mod bridge;
pub mod governance;
pub mod oracle;
pub mod zkp;
pub mod utils;

use subxt::{OnlineClient, PolkadotConfig};
use std::sync::Arc;

#[subxt::subxt(runtime_metadata_path = "metadata.scale")]
pub mod rechain {{}}

/// REChain SDK Configuration
#[derive(Clone, Debug)]
pub struct SDKConfig {
    pub endpoint: String,
    pub timeout: u64,
    pub retries: u32,
}

impl Default for SDKConfig {
    fn default() -> Self {
        Self {
            endpoint: "ws://localhost:9944".to_string(),
            timeout: 60000,
            retries: 3,
        }
    }
}

/// Complete REChain SDK Client
pub struct REChainSDK {
    client: OnlineClient<PolkadotConfig>,
    config: SDKConfig,
}

impl REChainSDK {
    /// Initialize new SDK instance
    pub async fn new(config: SDKConfig) -> Result<Self, Box<dyn std::error::Error>> {
        let client = OnlineClient::<PolkadotConfig>::from_url(&config.endpoint).await?;

        Ok(Self {
            client,
            config,
        })
    }}

/// SDK Error types
#[derive(Debug, Clone)]
pub enum SDKError {
    NetworkError(String),
    PalletError(String),
    ConfigurationError(String),
    TimeoutError(String),
}

impl std::fmt::Display for SDKError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SDKError::NetworkError(msg) => write!(f, "Network error: {}", msg),
            SDKError::PalletError(msg) => write!(f, "Pallet error: {}", msg),
            SDKError::ConfigurationError(msg) => write!(f, "Configuration error: {}", msg),
            SDKError::TimeoutError(msg) => write!(f, "Timeout error: {}", msg),
        }
    }
}

impl std::error::Error for SDKError {}

/// Helper functions
pub mod utils {
    use super::*;

    /// Generate keypair from seed
    pub fn generate_keypair(seed: &str) -> sp_core::sr25519::Pair {
        sp_core::sr25519::Pair::from_string(seed, None).unwrap_or_else(|_| {
            sp_core::sr25519::Pair::from_string("//Alice", None).expect("Should generate Alice key")
        })
    }

    /// Format balance for display
    pub fn format_balance(balance: u128, decimals: u32) -> String {
        let divisor = 10u128.pow(decimals);
        let integer_part = balance / divisor;
        let fractional_part = balance % divisor;

        format!("{}.{} RECH", integer_part, format!("{:0width$}", fractional_part, width = decimals as usize))
    }

    /// Convert address format
    pub fn convert_address(address: &str, target_format: u8) -> String {
        // Address conversion logic would go here
        address.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sdk_initialization() {
        let config = SDKConfig::default();
        let sdk = REChainSDK::new(config).await;

        assert!(sdk.is_ok());
    }

    #[test]
    fn test_balance_formatting() {
        let balance = 1000000000000000000; // 1 token with 18 decimals
        let formatted = utils::format_balance(balance, 18);

        assert_eq!(formatted, "1.000000000000000000 RECH");
    }
}
EOF

    print_status "Rust SDK generated successfully."
}

# Generate Python SDK
generate_python_sdk() {
    print_section "Generating Python SDK..."

    # Generate requirements.txt
    cat > "$OUTPUT_DIR/requirements.txt" << EOF
substrate-interface>=1.7.0
scalecodec>=1.2.0
websocket-client>=1.0.0
requests>=2.25.0
asyncio>=3.4.3
typing-extensions>=4.0.0
EOF

    # Generate main SDK file
    cat > "$OUTPUT_DIR/rechain_sdk.py" << EOF
"""
$PROJECT_NAME Python SDK - Generated by REChain Network Solutions LLC
Complete SDK for interacting with the REChain ecosystem
"""

import asyncio
import json
from typing import Optional, Dict, Any, List
from substrate_interface import SubstrateInterface, Keypair
from substrate_interface.exceptions import SubstrateRequestException


class REChainSDK:
    """Complete REChain SDK for Python applications"""

    def __init__(self, endpoint: str = "ws://localhost:9944"):
        """
        Initialize REChain SDK

        Args:
            endpoint: WebSocket endpoint URL
        """
        self.endpoint = endpoint
        self.interface: Optional[SubstrateInterface] = None
        self.keypair = Keypair.create_from_uri('//Alice')

    async def initialize(self) -> None:
        """Initialize SDK connection"""
        try:
            self.interface = SubstrateInterface(
                url=self.endpoint,
                type_registry_preset='substrate-node-template'
            )
            print("🚀 REChain SDK initialized successfully")
        except Exception as e:
            raise Exception(f"Failed to initialize SDK: {str(e)}")

    async def disconnect(self) -> None:
        """Disconnect SDK"""
        if self.interface:
            self.interface.close()
            self.interface = None

    async def create_proposal(self, title: str, description: str) -> Dict[str, Any]:
        """Create governance proposal"""
        if not self.interface:
            raise Exception("SDK not initialized")

        # Create proposal extrinsic
        call = self.interface.compose_call(
            call_module='Governance',
            call_function='create_proposal',
            call_params={{
                'title': title,
                'description': description,
                'metadata_hash': None
            }}
        )

        # Submit extrinsic
        extrinsic = self.interface.create_signed_extrinsic(call, keypair=self.keypair)

        try:
            receipt = self.interface.submit_extrinsic(extrinsic, wait_for_inclusion=True)
            return {
                'success': True,
                'hash': receipt['extrinsic_hash'],
                'block': receipt['block_hash']
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }

    async def register_domain(self, domain: str, content_hash: str) -> Dict[str, Any]:
        """Register Web4 domain"""
        if not self.interface:
            raise Exception("SDK not initialized")

        call = self.interface.compose_call(
            call_module='Web4',
            call_function='register_domain',
            call_params={{
                'domain': domain,
                'content_hash': content_hash
            }}
        )

        extrinsic = self.interface.create_signed_extrinsic(call, keypair=self.keypair)

        try:
            receipt = self.interface.submit_extrinsic(extrinsic, wait_for_inclusion=True)
            return {
                'success': True,
                'hash': receipt['extrinsic_hash']
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }

    async def create_token(self, name: str, symbol: str, decimals: int, supply: int) -> Dict[str, Any]:
        """Create DeFi token"""
        if not self.interface:
            raise Exception("SDK not initialized")

        call = self.interface.compose_call(
            call_module='DeFi',
            call_function='create_token',
            call_params={{
                'name': name,
                'symbol': symbol,
                'decimals': decimals,
                'total_supply': supply
            }}
        )

        extrinsic = self.interface.create_signed_extrinsic(call, keypair=self.keypair)

        try:
            receipt = self.interface.submit_extrinsic(extrinsic, wait_for_inclusion=True)
            return {
                'success': True,
                'hash': receipt['extrinsic_hash']
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }

    async def get_block_number(self) -> Optional[int]:
        """Get current block number"""
        if not self.interface:
            raise Exception("SDK not initialized")

        try:
            result = self.interface.get_block_number()
            return result
        except Exception:
            return None

    async def get_account_balance(self, account_address: str) -> Optional[int]:
        """Get account balance"""
        if not self.interface:
            raise Exception("SDK not initialized")

        try:
            result = self.interface.get_account_balance(account_address)
            return result
        except Exception:
            return None


# Utility functions
def format_balance(balance: int, decimals: int = 12) -> str:
    """Format balance for display"""
    divisor = 10 ** decimals
    integer_part = balance // divisor
    fractional_part = balance % divisor
    return f"{integer_part}.{fractional_part"0{decimals}d"} RECH"


def convert_address(address: str, target_format: int = 42) -> str:
    """Convert address format"""
    # Address conversion logic would go here
    return address


# Async context manager support
class SDKContext:
    """Async context manager for SDK"""

    def __init__(self, endpoint: str = "ws://localhost:9944"):
        self.endpoint = endpoint
        self.sdk = REChainSDK(endpoint)

    async def __aenter__(self) -> REChainSDK:
        await self.sdk.initialize()
        return self.sdk

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.sdk.disconnect()


# Example usage
async def example_usage():
    """Example of how to use the SDK"""
    async with SDKContext() as sdk:
        # Get current block number
        block_number = await sdk.get_block_number()
        print(f"Current block: {block_number}")

        # Create governance proposal
        result = await sdk.create_proposal(
            "Improve Network Security",
            "This proposal aims to enhance network security"
        )
        print(f"Proposal result: {result}")

        # Register domain
        domain_result = await sdk.register_domain(
            "example.web4",
            "QmYwAPJzv5CZsnAztmj5DrE8yQkCjXaieQaxZ"
        )
        print(f"Domain result: {domain_result}")


if __name__ == "__main__":
    # Run example
    asyncio.run(example_usage())
EOF

    print_status "Python SDK generated successfully."
}

# Main generation logic
main() {
    print_status "=== REChain Network Solutions LLC - SDK Generator ==="

    case "$LANGUAGE" in
        "typescript")
            generate_typescript_sdk
            ;;
        "rust")
            generate_rust_sdk
            ;;
        "python")
            generate_python_sdk
            ;;
        "all")
            generate_typescript_sdk
            generate_rust_sdk
            generate_python_sdk
            ;;
        *)
            echo "Error: Unsupported language: $LANGUAGE"
            echo "Supported languages: typescript, rust, python, all"
            exit 1
            ;;
    esac

    print_status "🎉 SDK generation completed!"
    print_status ""
    print_status "=== Generated SDK Information ==="
    print_status "Output Directory: $OUTPUT_DIR"
    print_status "Project Name: $PROJECT_NAME"
    print_status "Language: $LANGUAGE"
    print_status ""
    print_status "Next Steps:"
    print_status "1. cd $OUTPUT_DIR"
    print_status "2. Install dependencies (npm install / cargo build / pip install -r requirements.txt)"
    print_status "3. Check the README.md for usage examples"
    print_status "4. Start building your application!"
}

# Handle script arguments
case "${1:-}" in
    "help"|"-h"|"--help")
        echo "Usage: $0 [PROJECT_NAME] [LANGUAGE] [OUTPUT_DIR]"
        echo ""
        echo "Arguments:"
        echo "  PROJECT_NAME  Name of your project (default: rechain-dapp)"
        echo "  LANGUAGE      SDK language: typescript|rust|python|all (default: typescript)"
        echo "  OUTPUT_DIR    Output directory (default: ./sdk)"
        echo ""
        echo "Examples:"
        echo "  $0                          # Generate TypeScript SDK with defaults"
        echo "  $0 my-dapp                  # Generate TypeScript SDK for 'my-dapp'"
        echo "  $0 my-dapp rust            # Generate Rust SDK for 'my-dapp'"
        echo "  $0 my-dapp all ./custom   # Generate all SDKs in ./custom directory"
        exit 0
        ;;
    *)
        main
        ;;
esac