[package]
name = "rechain-node-core-approval-voting-parallel"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Approval Voting Subsystem running approval work in parallel"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
gum = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }

rechain-approval-distribution = { workspace = true, default-features = true }
rechain-node-core-approval-voting = { workspace = true, default-features = true }
rechain-node-metrics = { workspace = true, default-features = true }
rechain-node-network-protocol = { workspace = true, default-features = true }
rechain-node-primitives = { workspace = true, default-features = true }
rechain-node-subsystem = { workspace = true, default-features = true }
rechain-node-subsystem-util = { workspace = true, default-features = true }
rechain-overseer = { workspace = true, default-features = true }
rechain-primitives = { workspace = true, default-features = true }

sc-keystore = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false, features = ["full_crypto"] }
sp-consensus = { workspace = true, default-features = false }
sp-consensus-slots = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }

rand = { workspace = true }
rand_chacha = { workspace = true }
rand_core = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
kvdb-memorydb = { workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true }
rechain-node-subsystem-test-helpers = { workspace = true, default-features = true }
rechain-primitives-test-helpers = { workspace = true, default-features = true }
rechain-subsystem-bench = { workspace = true, default-features = true }
schnorrkel = { workspace = true, default-features = true }
sp-consensus-babe = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-keystore = { workspace = true, default-features = true }
sp-tracing = { workspace = true }

