name: rustdoc
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build docs
        run: cargo doc --workspace --no-deps -Zrustdoc-map | cat
